const redis = require('redis');
const { exec } = require('child_process');
const fs = require('fs');
const util = require('util');
const path = require('path');
const execPromise = util.promisify(exec);

const redisClient = redis.createClient({ url: 'redis://127.0.0.1:6379' });

const CORE_DIR = path.resolve('../core');
const WORK_DIR = path.resolve('../run_env'); 

async function processJob(job) {
    console.log(`\n========================================`);
    console.log(`[Worker] Starting Job: ${job.job_id} for Team: ${job.team}`);
    
    // 1. Setup the Isolated Directory for this specific job
    const jobDir = path.join(WORK_DIR, job.job_id);
    if (!fs.existsSync(jobDir)) fs.mkdirSync(jobDir, { recursive: true });

    // Move the uploaded file from /uploads into the job's sandbox directory
    const sandboxCodePath = path.join(jobDir, 'submission.cpp');
    fs.renameSync(job.filepath, sandboxCodePath);

    try {
        console.log(`[Worker] Spinning up Docker Sandbox...`);
        
        // 2. RUN THE DOCKER CONTAINER
        // --rm: Delete container when finished
        // --network none: No internet access
        // -v: Mount the specific job directory to /sandbox
        const dockerCmd = `docker run --rm --network none -v ${jobDir}:/sandbox hft-sandbox`;
        
        const { stdout, stderr } = await execPromise(dockerCmd);
        console.log(stdout); // Prints the logs from runner.sh

        // 3. Run the Golden Model (On the Mac Host)
        console.log(`[Worker] Verifying Correctness...`);
        const { stdout: pyOut } = await execPromise(`python3 ${CORE_DIR}/golden_model.py ${jobDir}`);
        
        if (pyOut.includes("SUCCESS")) {
            console.log(`[Worker] Correctness Passed!`);
            
            // 4. Score the submission by reading the latency.txt file generated by the Docker container
            const latencyFilePath = path.join(jobDir, 'latency.txt');
            if (fs.existsSync(latencyFilePath)) {
                const latencyStr = fs.readFileSync(latencyFilePath, 'utf8');
                const actualLatency = parseInt(latencyStr.trim(), 10);
                
                console.log(`[Worker] Official Score: ${actualLatency} ns`);
                await redisClient.zAdd('leaderboard', { score: actualLatency, value: job.team });
            } else {
                console.error(`[Worker ERROR] latency.txt was not generated!`);
            }
        } else {
            console.log(`[Worker] Correctness FAILED:\n${pyOut}`);
        }

    } catch (err) {
        console.error(`[Worker ERROR]`, err.message);
    } finally {
        // Optional Cleanup
        // if (fs.existsSync(jobDir)) fs.rmSync(jobDir, { recursive: true, force: true });
    }
}

// Redis Worker Loop
async function startWorker() {
    await redisClient.connect();
    console.log('[Worker] Connected to Redis. Waiting for submissions...');

    while (true) {
        try {
            // brPop blocks the loop until a job appears in the queue
            const result = await redisClient.brPop('hackathon:queue', 0);
            const job = JSON.parse(result.element);
            
            // Await ensures we finish grading one submission before starting the next
            await processJob(job);
        } catch (err) {
            console.error('Redis pulling error:', err);
        }
    }
}

// Boot up the worker
startWorker();