#include <arpa/inet.h>
#include <atomic>
#include <chrono>
#include <cinttypes>
#include <cstring>
#include <iostream>
#include <mutex>
#include <random>
#include <sys/socket.h>
#include <thread>
#include <unistd.h>
#include <vector>

// Steady clock is a monotonic clock ideal for measuring intervals.
// It won't be affected by system clock changes.
// System clock can move backwards to sync with NTP.
using Clock = std::chrono::steady_clock;

static constexpr const char *ENGINE_HOST = "127.0.0.1";
static constexpr uint16_t ENGINE_PORT = 8080;

static constexpr int NUM_INSTRUMENTS = 4; // instruments numbered 1..N
static constexpr int BASE = 10000;        // instrument I trades around BASE * I
static constexpr int BOOK_DEPTH = 10; // price levels per side per market maker
static constexpr int SPREAD_TICK = 2; // ticks between consecutive levels

// How long to stay in each phase (seconds)
static constexpr int WARMUP = 3;
static constexpr int RAMP = 5;
static constexpr int SUSTAIN = 5;
static constexpr int SPIKE = 5;
static constexpr int SLA_HUNT = 5;

// Sequence IDs that will never be generated by the global counter which starts
// at 1 and advances sequentially).
static constexpr uint64_t SEQ_MIN = 8000000;
static constexpr uint64_t SEQ_MAX = 9999999;

enum class Phase : uint8_t {
  EDGE_CASES = 0,
  WARMUP,
  RAMP,
  SUSTAIN,
  SPIKE,
  SLA_HUNT,
  DONE
};

static std::atomic<Phase> PHASE{Phase::EDGE_CASES};
static std::atomic<bool> SHUTDOWN{false};
static std::atomic<uint64_t> SEQ{1};
static std::atomic<uint64_t> NETWORK_ORDERS_SENT{0};

// Generate the next unique sequence ID for orders.
// Uses relaxed memory order since we only care about uniqueness, not strict
// ordering.
inline uint64_t NextSeq() {
  return SEQ.fetch_add(1, std::memory_order_relaxed);
}

// Calculate the mid price for a given instrument.
// Mids are spaced BASE apart, so instr 1 trades around 10000, instr 2 around
// 20000, etc.
inline uint64_t MidFor(uint16_t instr) {
  return static_cast<uint64_t>(BASE) * instr;
}

enum class Side : uint8_t { BUY = 1, SELL = 2 };
enum class OrderType : uint8_t { LIMIT = 1, MARKET = 2, CANCEL = 3 };

int ConnectToEngine() {
  // AF_INET = IPv4, SOCK_STREAM = TCP, 0 : default protocol (TCP for
  // SOCK_STREAM)
  int sock = socket(AF_INET, SOCK_STREAM, 0);
  if (sock < 0)
    return -1;

  sockaddr_in addr{}; // Zero-initialize the structure to avoid garbage values
                      // in padding bytes
  addr.sin_family = AF_INET; // IPv4
  addr.sin_port = htons(ENGINE_PORT);
  inet_pton(AF_INET, ENGINE_HOST,
            &addr.sin_addr); // Convert IP string to binary form

  int res =
      connect(sock, reinterpret_cast<struct sockaddr *>(&addr), sizeof(addr));
  if (res < 0) {
    close(sock);
    return -1;
  }
  return sock;
}

// Format one order into buf.
// Returns bytes written.
// to print uint64_t, we use %llu on Mac and %lu on Linux. The PRIu64 macro from
// <cinttypes> handles this for us.
int WriteOrder(char *buf, size_t max, uint64_t seq, uint32_t client,
               uint16_t instr, OrderType type, uint64_t price, uint32_t qty,
               Side side) {
  return snprintf(buf, max,
                  "{"
                  "\"s\": %" PRIu64 ", \"c\": %u"
                  ", \"i\": %u"
                  ", \"t\": %d"
                  ", \"p\": %" PRIu64 ", \"q\": %u"
                  ", \"side\": %d"
                  "}\n",
                  seq, client, instr, static_cast<int>(type), price, qty,
                  static_cast<int>(side));
}

// Send one limit/market order. seq_id must be a fresh NextSeq().
bool SendOrder(int sock, uint64_t seq, uint32_t client, uint16_t instr,
               uint64_t price, uint32_t qty, Side side) {
  char buf[256];
  int len = WriteOrder(buf, sizeof(buf), seq, client, instr, OrderType::LIMIT,
                       price, qty, side);
  const bool sent = send(sock, buf, len, 0) == len;
  if (sent) {
    NETWORK_ORDERS_SENT.fetch_add(1, std::memory_order_relaxed);
  }
  return sent;
}

// Send a cancel. seq gets a fresh ID, price gets overloaded with target_seq.
bool SendCancel(int sock, uint64_t target_seq, uint32_t client, uint16_t instr,
                Side side) {
  char buf[256];
  // We generate a NextSeq() for the cancel order and pass target_seq into the
  // price parameter.
  int len = WriteOrder(buf, sizeof(buf), NextSeq(), client, instr,
                       OrderType::CANCEL, target_seq, 0, side);
  const bool sent = send(sock, buf, len, 0) == len;
  if (sent) {
    NETWORK_ORDERS_SENT.fetch_add(1, std::memory_order_relaxed);
  }
  return sent;
}

// Rate limiter: 1s window

struct RateLimiter {

  int target_per_sec;
  int ops_this_window{0};
  Clock::time_point window_start{Clock::now()};

  explicit RateLimiter(int tps) : target_per_sec(tps) {}

  void SetRate(int tps) { target_per_sec = tps; }

  // Call after each send.
  void Throttle() {
    ops_this_window++;
    if (ops_this_window >= target_per_sec) {
      auto elapsed = Clock::now() - window_start;
      auto budget = std::chrono::seconds(1);
      if (elapsed < budget)
        std::this_thread::sleep_for(budget - elapsed);
      window_start = Clock::now();
      ops_this_window = 0;
    }
  }
};

// =============================================================================
// Bot 1 — Market Maker
//
// Continuously posts BOOK_DEPTH bids and asks around mid.
// Refreshes every REFRESH_MS by cancelling all resting orders and re-posting.
// Rate scales with phase: 200 → 500 → 800 → 1500 orders/sec.
// =============================================================================

struct RestingOrder {
  uint64_t seq_id;
  Side side;
};

void MarketMakerBot(uint32_t client_id, uint16_t instr_id) {
  int sock = ConnectToEngine();
  if (sock < 0) {
    std::cerr << "[MM " << client_id << "] Connection failed\n";
    return;
  }

  static constexpr int REFRESH_MS = 2000;

  uint64_t mid = MidFor(instr_id);

  // different seed per bot
  std::mt19937 rng(client_id * 6364136223846793005ULL);

  std::vector<RestingOrder> resting;
  resting.reserve(BOOK_DEPTH * 2);

  RateLimiter rl(200);
  auto last_refresh = Clock::now();

  auto post_book = [&]() {
    for (int i = 1; i <= BOOK_DEPTH && !SHUTDOWN.load(); i++) {
      uint64_t bid_price = mid - static_cast<uint64_t>(i * SPREAD_TICK);
      uint64_t ask_price = mid + static_cast<uint64_t>(i * SPREAD_TICK);

      uint32_t qty = static_cast<uint32_t>(10 + (BOOK_DEPTH - i) * 5);

      uint64_t bid_seq = NextSeq();
      SendOrder(sock, bid_seq, client_id, instr_id, bid_price, qty, Side::BUY);
      resting.push_back({bid_seq, Side::BUY});
      rl.Throttle();

      uint64_t ask_seq = NextSeq();
      SendOrder(sock, ask_seq, client_id, instr_id, ask_price, qty, Side::SELL);
      resting.push_back({ask_seq, Side::SELL});
      rl.Throttle();
    }
  };

  auto cancel_all = [&]() {
    for (const auto &o : resting)
      SendCancel(sock, o.seq_id, client_id, instr_id, o.side);
    resting.clear();
  };

  while (!SHUTDOWN.load()) {
    Phase p = PHASE.load();
    if (p == Phase::DONE)
      break;
    else if (p == Phase::RAMP)
      rl.SetRate(500);
    else if (p == Phase::SUSTAIN)
      rl.SetRate(800);
    else if (p == Phase::SLA_HUNT)
      rl.SetRate(1500);
    else
      rl.SetRate(200);

    // Refresh: cancel stale resting orders and re-post at current mid
    auto now = Clock::now();
    auto time_elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(
                            now - last_refresh)
                            .count();
    if (time_elapsed > REFRESH_MS) {
      cancel_all();
      last_refresh = Clock::now();
    }

    post_book();

    // Slight mid drift
    uint64_t drift = rng() % 3;
    uint64_t drift_val = drift * SPREAD_TICK;
    if (rng() % 2 == 0)
      mid += drift_val;
    else
      mid = (mid > drift_val) ? mid - drift_val : mid;
    mid = std::max(mid, static_cast<uint64_t>(BASE / 2));
  }

  cancel_all();
  close(sock);
  std::cout << "[MM " << client_id << "] Exiting.\n";
}

// =============================================================================
// Bot 2 — Aggressive Taker
//
// Inactive during EDGE_CASES and WARMUP (lets the book build up first).
// Two behaviours, chosen randomly:
//   • Simple cross (75%): bid just above best ask / ask just below best bid.
//     Tests the single-match path.
//   • Deep sweep (25%): one huge bid or ask that crosses all BOOK_DEPTH
//     levels. Tests the O(n) matching loop and is the primary driver of
//     SLA breaches in the later phases.
// =============================================================================

void AggressiveTakerBot(uint32_t client_id) {
  int sock = ConnectToEngine();
  if (sock < 0) {
    std::cerr << "[Taker " << client_id << "] Connection failed\n";
    return;
  }

  std::mt19937 rng(client_id * 2654435761ULL);
  std::uniform_int_distribution<int> instr_dist(1, NUM_INSTRUMENTS);

  RateLimiter rl(50);

  while (!SHUTDOWN.load()) {
    Phase p = PHASE.load();
    if (p == Phase::EDGE_CASES || p == Phase::WARMUP) {
      std::this_thread::sleep_for(std::chrono::milliseconds(500));
      continue;
    }
    if (p == Phase::DONE)
      break;
    else if (p == Phase::SUSTAIN)
      rl.SetRate(200);
    else if (p == Phase::SLA_HUNT)
      rl.SetRate(600);
    else
      rl.SetRate(50);

    uint16_t instr = static_cast<uint16_t>(instr_dist(rng));
    uint64_t mid = MidFor(instr);

    bool do_sweep = (rng() % 4 == 0); // 25% deep sweeps

    if (do_sweep) {
      uint64_t edge = static_cast<uint64_t>(SPREAD_TICK * (BOOK_DEPTH + 2));
      uint32_t sweep_qty = 500;
      SendOrder(sock, NextSeq(), client_id, instr, mid + edge, sweep_qty,
                Side::BUY);
      rl.Throttle();
      SendOrder(sock, NextSeq(), client_id, instr, mid - edge, sweep_qty,
                Side::SELL);
      rl.Throttle();

    } else {
      uint64_t tick = static_cast<uint64_t>(SPREAD_TICK);
      SendOrder(sock, NextSeq(), client_id, instr, mid + tick + 1, 10,
                Side::BUY);
      rl.Throttle();
      SendOrder(sock, NextSeq(), client_id, instr, mid - tick - 1, 10,
                Side::SELL);
      rl.Throttle();
    }
  }

  close(sock);
  std::cout << "[Taker " << client_id << "] Exiting.\n";
}

// =============================================================================
// Bot 3 — Cancel Spammer
//
// Tests two distinct cancel paths:
//   • Phantom cancel: fires cancels for sequence IDs that were never created.
//     The engine must return gracefully without corrupting book state.
//   • Hot cancel: posts a resting order then immediately cancels it.
// Rate ramps with phase. Phantom probes are interspersed in all phases.
// =============================================================================

void CancelSpammerBot(uint32_t client_id) {
  int sock = ConnectToEngine();
  if (sock < 0) {
    std::cerr << "[Canceler " << client_id << "] Connection failed\n";
    return;
  }

  std::mt19937 rng(client_id * 31337ULL);
  std::uniform_int_distribution<int> instr_dist(1, NUM_INSTRUMENTS);
  std::uniform_int_distribution<uint64_t> phantom_dist(SEQ_MIN, SEQ_MAX);

  RateLimiter rl(100);

  while (!SHUTDOWN.load()) {
    Phase p = PHASE.load();
    if (p == Phase::DONE)
      break;
    else if (p == Phase::RAMP || p == Phase::SUSTAIN)
      rl.SetRate(300);
    else if (p == Phase::SLA_HUNT)
      rl.SetRate(800);
    else
      rl.SetRate(100);

    uint16_t instr = static_cast<uint16_t>(instr_dist(rng));
    uint64_t mid = MidFor(instr);

    // Use a seq_id from a range the global counter will never reach
    SendCancel(sock, phantom_dist(rng), client_id, instr, Side::BUY);
    rl.Throttle();

    // Far from mid so doesn't match
    uint64_t real_seq = NextSeq();
    SendOrder(sock, real_seq, client_id, instr, mid - 200, 1, Side::BUY);
    rl.Throttle();
    SendCancel(sock, real_seq, client_id, instr, Side::BUY);
    rl.Throttle();

    // Cancel an order that was just cancelled.
    if (rng() % 8 == 0) {
      SendCancel(sock, real_seq, client_id, instr, Side::BUY);
      rl.Throttle();
    }
  }

  close(sock);
  std::cout << "[Canceler " << client_id << "] Exiting.\n";
}

// =============================================================================
// Bot 4 — Wash Trader
//
// A single client_id submits a resting bid, then submits a crossing ask.
// The engine MUST reject the incoming ask (not the resting bid) and emit
// no trade.
// =============================================================================

void WashTraderBot(uint32_t client_id) {
  int sock = ConnectToEngine();
  if (sock < 0) {
    std::cerr << "[WashTrader " << client_id << "] Connection failed\n";
    return;
  }

  std::mt19937 rng(client_id * 999983ULL);
  std::uniform_int_distribution<int> instr_dist(1, NUM_INSTRUMENTS);

  while (!SHUTDOWN.load()) {
    Phase p = PHASE.load();
    if (p == Phase::DONE)
      break;

    uint16_t instr = static_cast<uint16_t>(instr_dist(rng));
    uint64_t mid = MidFor(instr);

    uint64_t bid_seq = NextSeq();
    SendOrder(sock, bid_seq, client_id, instr, mid, 10, Side::BUY);
    usleep(8000); // 8ms — give the dispatcher time to enqueue it
    SendOrder(sock, NextSeq(), client_id, instr, mid - 1, 10, Side::SELL);
    usleep(8000);
    // clean up the resting bid in case the engine didn't reject the crossing
    // ask
    SendCancel(sock, bid_seq, client_id, instr, Side::BUY);

    std::this_thread::sleep_for(std::chrono::milliseconds(250));
  }

  close(sock);
  std::cout << "[WashTrader " << client_id << "] Exiting.\n";
}

// =============================================================================
// Bot 5 — Flood Bot
//
// Only active during SPIKE and SLA_HUNT. Fires limit orders as fast as the
// socket will accept them, no rate limiter. Random instrument, random price
// (far from mid to avoid constant matching slowing the loop),
// qty=1 to minimise per-order work in the engine.
//
// The goal is to maximise queue depth so the dispatcher thread cannot drain
// fast enough.
// =============================================================================

void FloodBot(uint32_t client_id) {
  int sock = ConnectToEngine();
  if (sock < 0) {
    std::cerr << "[Flood " << client_id << "] Connection failed\n";
    return;
  }

  std::mt19937 rng(client_id * 1234567891ULL);
  std::uniform_int_distribution<int> instr_dist(1, NUM_INSTRUMENTS);
  std::uniform_int_distribution<uint64_t> price_dist(1000, 5000);

  while (!SHUTDOWN.load()) {
    Phase p = PHASE.load();
    if (p != Phase::SPIKE && p != Phase::SLA_HUNT) {
      std::this_thread::sleep_for(std::chrono::milliseconds(200));
      continue;
    }
    if (p == Phase::DONE)
      break;
    uint16_t instr = static_cast<uint16_t>(instr_dist(rng));
    uint64_t price = price_dist(rng);
    Side side = (rng() % 2) ? Side::BUY : Side::SELL;
    SendOrder(sock, NextSeq(), client_id, instr, price, 1, side);
  }

  close(sock);
  std::cout << "[Flood " << client_id << "] Exiting.\n";
}

// =============================================================================
// Phase 1 — Edge Cases (runs before any bot threads launch)
//
// Single-connection, sequential, so every scenario is deterministic and easy
// to verify against input_ledger.csv + trade_ledger.csv after the run.
// =============================================================================

void RunEdgeCases() {
  std::cout << "\n[Fleet] ── Phase 1: Edge Cases ──────────────────────────\n";

  int sock = ConnectToEngine();
  if (sock < 0) {
    std::cerr << "[Edge] Could not connect — is the engine running?\n";
    return;
  }

  // ── EC-1: Phantom cancel ──────────────────────────────────────────────
  // Cancel a sequence ID that has never been submitted.
  // Expected: engine returns silently, book unchanged.
  std::cout << "[EC-1] Phantom cancel (seq 999999)...\n";
  SendCancel(sock, 999999, 1, 1, Side::BUY);
  usleep(20000);

  // ── EC-2: Multi-level swept book ─────────────────────────────────────
  // Three resting asks at 10002, 10004, 10006.
  // One aggressive bid at 10010 with qty=50 sweeps all three.
  // Expected: 3 trades generated, bid remainder (if any) rests or exhausts.
  std::cout << "[EC-2] Multi-level sweep...\n";
  uint64_t ask1 = NextSeq();
  SendOrder(sock, ask1, 2, 1, 10002, 10, Side::SELL);
  uint64_t ask2 = NextSeq();
  SendOrder(sock, ask2, 2, 1, 10004, 10, Side::SELL);
  uint64_t ask3 = NextSeq();
  SendOrder(sock, ask3, 2, 1, 10006, 10, Side::SELL);
  usleep(10000);
  SendOrder(sock, NextSeq(), 1, 1, 10010, 50, Side::BUY);
  usleep(20000);

  // ── EC-3: Wash trade attempt ──────────────────────────────────────────
  // Client 99 rests a bid then crosses it with its own ask.
  // Expected: ask rejected (or cancelled), NO trade, bid still resting.
  std::cout << "[EC-3] Wash trade (client 99)...\n";
  uint64_t wash_bid = NextSeq();
  SendOrder(sock, wash_bid, 99, 1, 10000, 10, Side::BUY);
  usleep(10000);
  SendOrder(sock, NextSeq(), 99, 1, 9999, 10, Side::SELL); // crossing ask
  usleep(10000);
  SendCancel(sock, wash_bid, 99, 1, Side::BUY); // clean up
  usleep(10000);

  // ── EC-4: Partial fill then cancel remainder ──────────────────────────
  // Client 3 rests a large ask (qty=100).
  // Client 4 partially fills it (qty=30). Client 3 then cancels remainder (70).
  // Expected: 1 trade for 30, then ask disappears from final_book.csv.
  std::cout << "[EC-4] Partial fill + cancel remainder...\n";
  uint64_t big_ask = NextSeq();
  SendOrder(sock, big_ask, 3, 2, 19998, 100, Side::SELL); // instr 2
  usleep(10000);
  SendOrder(sock, NextSeq(), 4, 2, 20010, 30, Side::BUY); // partial fill
  usleep(10000);
  SendCancel(sock, big_ask, 3, 2, Side::SELL); // cancel unfilled remainder
  usleep(20000);

  // ── EC-5: Duplicate sequence ID ──────────────────────────────────────
  // Submit seq=DUP twice with different prices.
  // Expected: second submission is ignored / rejected; book has only one
  // order at DUP's original price.
  std::cout << "[EC-5] Duplicate sequence ID...\n";
  uint64_t dup = NextSeq();
  SendOrder(sock, dup, 5, 1, 9500, 10, Side::BUY);
  usleep(5000);
  SendOrder(sock, dup, 5, 1, 9600, 10, Side::BUY); // same seq, different price
  usleep(20000);

  // ── EC-6: Cancel of an already fully filled order ─────────────────────
  // Post two matching orders (immediate fill). Then cancel the maker's seq.
  // Expected: cancel is a no-op (order no longer rests), no crash.
  std::cout << "[EC-6] Cancel of already-filled order...\n";
  uint64_t filled_maker = NextSeq();
  SendOrder(sock, filled_maker, 6, 3, 29998, 5, Side::SELL); // instr 3
  usleep(5000);
  SendOrder(sock, NextSeq(), 7, 3, 30010, 5, Side::BUY); // immediate match
  usleep(10000);
  SendCancel(sock, filled_maker, 6, 3, Side::SELL); // should be a no-op
  usleep(20000);

  close(sock);
  std::cout << "[Fleet] Phase 1 complete.\n\n";
}

int main() {

  std::cout << "\n[Fleet] Starting bot fleet...\n";

  PHASE.store(Phase::EDGE_CASES);
  RunEdgeCases();

  std::vector<std::thread> threads;

  // Market makers: 2 per instrument, keeps the book dense
  for (int instr = 1; instr <= NUM_INSTRUMENTS; ++instr) {
    uint32_t mm1 = 100 + instr;
    uint32_t mm2 = 200 + instr;
    threads.emplace_back(MarketMakerBot, mm1, static_cast<uint16_t>(instr));
    threads.emplace_back(MarketMakerBot, mm2, static_cast<uint16_t>(instr));
  }

  // Aggressive takers: 3 bots.
  // Each independently picks instruments at random, so all instruments
  // get hit and instrument-level concurrency is tested.
  threads.emplace_back(AggressiveTakerBot, 301);
  threads.emplace_back(AggressiveTakerBot, 302);
  threads.emplace_back(AggressiveTakerBot, 303);

  // Cancel spammers: 2 bots
  threads.emplace_back(CancelSpammerBot, 401);
  threads.emplace_back(CancelSpammerBot, 402);

  // Wash trader: 1 bot
  threads.emplace_back(WashTraderBot, 501);

  // Flood bots: 4 bots, dormant until SPIKE/SLA_HUNT.
  threads.emplace_back(FloodBot, 601);
  threads.emplace_back(FloodBot, 602);
  threads.emplace_back(FloodBot, 603);
  threads.emplace_back(FloodBot, 604);

  // Total threads connecting: 8 MMs + 3 takers + 2 cancelers + 1 wash + 4 flood
  // = 18

  // Give bots a moment to connect before we start clocking phases
  std::this_thread::sleep_for(std::chrono::milliseconds(800));

  auto announce = [](const char *name, int seconds) {
    std::cout << "[Fleet] " << name << " (" << seconds << "s) \n" << std::flush;
  };

  announce("Phase 2: Warm-up", WARMUP);
  PHASE.store(Phase::WARMUP);
  std::this_thread::sleep_for(std::chrono::seconds(WARMUP));

  announce("Phase 3: Ramp", RAMP);
  PHASE.store(Phase::RAMP);
  std::this_thread::sleep_for(std::chrono::seconds(RAMP));

  announce("Phase 4: Sustain", SUSTAIN);
  PHASE.store(Phase::SUSTAIN);
  std::this_thread::sleep_for(std::chrono::seconds(SUSTAIN));

  announce("Phase 5: Spike", SPIKE);
  PHASE.store(Phase::SPIKE);
  std::this_thread::sleep_for(std::chrono::seconds(SPIKE));

  announce("Phase 6: SLA Hunt", SLA_HUNT);
  PHASE.store(Phase::SLA_HUNT);
  std::this_thread::sleep_for(std::chrono::seconds(SLA_HUNT));

  std::cout << "\n[Fleet] All phases complete. Signalling shutdown.\n";
  PHASE.store(Phase::DONE);
  SHUTDOWN.store(true);

  for (auto &t : threads)
    if (t.joinable())
      t.join();

  std::cout << "[Fleet] Orders sent over network: "
            << NETWORK_ORDERS_SENT.load() << "\n";
  std::cout << "[Fleet] All bots exited. Check CSVs and latency.txt.\n\n";

  return 0;
}