#include "Order.h"
#include <arpa/inet.h>
#include <atomic>
#include <chrono>
#include <cstring>
#include <iostream>
#include <mutex>
#include <random>
#include <signal.h>
#include <string>
#include <sys/socket.h>
#include <thread>
#include <unistd.h>
#include <cstdint>
#include <vector>

// Steady clock is a monotonic clock ideal for measuring intervals.
// It won't be affected by system clock changes.
// System clock can move backwards to sync with NTP.
using Clock = std::chrono::steady_clock;

static const char *ENGINE_HOST = "127.0.0.1";
static uint16_t ENGINE_PORT = 8080;

static constexpr int NUM_INSTRUMENTS = 4; // instruments numbered 1..N
static constexpr int BASE = 10000;        // instrument I trades around BASE * I
static constexpr int BOOK_DEPTH = 10; // price levels per side per market maker
static constexpr int SPREAD_TICK = 2; // ticks between consecutive levels

// Shared load-test phase durations (seconds). All shards align to the worker's
// test_starts_at so late joiners enter at the current global phase.
static constexpr int WARMUP_SEC = 3;
static constexpr int RAMP_SEC = 5;
static constexpr int SUSTAIN_SEC = 5;
static constexpr int SPIKE_SEC = 5;

static constexpr uint64_t WARMUP_END_MS = static_cast<uint64_t>(WARMUP_SEC) * 1000;
static constexpr uint64_t RAMP_END_MS = WARMUP_END_MS + static_cast<uint64_t>(RAMP_SEC) * 1000;
static constexpr uint64_t SUSTAIN_END_MS = RAMP_END_MS + static_cast<uint64_t>(SUSTAIN_SEC) * 1000;
static constexpr uint64_t SPIKE_END_MS = SUSTAIN_END_MS + static_cast<uint64_t>(SPIKE_SEC) * 1000;

// Sequence IDs that will never be generated by the global counter which starts
// at 1 and advances sequentially).
static constexpr uint64_t SEQ_MIN = 8000000;
static constexpr uint64_t SEQ_MAX = 9999999;

enum class FleetPhase : uint8_t {
  WARMUP,
  RAMP,
  SUSTAIN,
  SPIKE,
  SLA_HUNT,
  DONE
};

static std::atomic<FleetPhase> PHASE{FleetPhase::WARMUP};
static std::atomic<bool> SHUTDOWN{false};
static std::atomic<uint64_t> SEQ{1};
static std::atomic<uint64_t> NETWORK_ORDERS_SENT{0};
static std::atomic<uint64_t> CONNECTIONS_ESTABLISHED{0};

inline uint64_t NowEpochMs() {
  return static_cast<uint64_t>(
      std::chrono::duration_cast<std::chrono::milliseconds>(
          std::chrono::system_clock::now().time_since_epoch())
          .count());
}

void RequestGracefulShutdown(const char *reason) {
  if (SHUTDOWN.exchange(true))
    return;
  PHASE.store(FleetPhase::DONE);
  std::cout << "[Fleet] " << reason << "\n";
}

const char *FleetPhaseName(FleetPhase phase) {
  switch (phase) {
  case FleetPhase::WARMUP:
    return "WARMUP";
  case FleetPhase::RAMP:
    return "RAMP";
  case FleetPhase::SUSTAIN:
    return "SUSTAIN";
  case FleetPhase::SPIKE:
    return "SPIKE";
  case FleetPhase::SLA_HUNT:
    return "SLA_HUNT";
  case FleetPhase::DONE:
    return "DONE";
  }
  return "UNKNOWN";
}

FleetPhase FleetPhaseForElapsedMs(uint64_t elapsed_ms) {
  if (elapsed_ms < WARMUP_END_MS)
    return FleetPhase::WARMUP;
  if (elapsed_ms < RAMP_END_MS)
    return FleetPhase::RAMP;
  if (elapsed_ms < SUSTAIN_END_MS)
    return FleetPhase::SUSTAIN;
  if (elapsed_ms < SPIKE_END_MS)
    return FleetPhase::SPIKE;
  return FleetPhase::SLA_HUNT;
}

void RunPhaseController(uint64_t test_starts_at_ms, uint64_t local_epoch_ms) {
  FleetPhase last_phase = FleetPhase::WARMUP;
  const uint64_t phase_epoch_ms =
      test_starts_at_ms > 0 ? test_starts_at_ms : local_epoch_ms;

  while (!SHUTDOWN.load()) {
    const uint64_t now = NowEpochMs();
    const uint64_t elapsed_ms = now > phase_epoch_ms ? now - phase_epoch_ms : 0;
    const FleetPhase next_phase = FleetPhaseForElapsedMs(elapsed_ms);

    if (next_phase != last_phase) {
      PHASE.store(next_phase);
      std::cout << "[Fleet] Load phase → " << FleetPhaseName(next_phase) << " (t="
                << (elapsed_ms / 1000) << "s)\n";
      last_phase = next_phase;
    }

    std::this_thread::sleep_for(std::chrono::milliseconds(100));
  }
}

// Generate the next unique sequence ID for orders.
// Uses relaxed memory order since we only care about uniqueness, not strict
// ordering.
inline uint64_t NextSeq() {
  return SEQ.fetch_add(1, std::memory_order_relaxed);
}

// Calculate the mid price for a given instrument.
// Mids are spaced BASE apart, so instr 1 trades around 10000, instr 2 around
// 20000, etc.
inline uint64_t MidFor(uint16_t instr) {
  return static_cast<uint64_t>(BASE) * instr;
}

int ConnectToEngine() {
  // AF_INET = IPv4, SOCK_STREAM = TCP, 0 : default protocol (TCP for
  // SOCK_STREAM)
  int sock = socket(AF_INET, SOCK_STREAM, 0);
  if (sock < 0)
    return -1;

  sockaddr_in addr{}; // Zero-initialize the structure to avoid garbage values
                      // in padding bytes
  addr.sin_family = AF_INET; // IPv4
  addr.sin_port = htons(ENGINE_PORT);
  inet_pton(AF_INET, ENGINE_HOST,
            &addr.sin_addr); // Convert IP string to binary form

  int res =
      connect(sock, reinterpret_cast<struct sockaddr *>(&addr), sizeof(addr));
  if (res < 0) {
    close(sock);
    return -1;
  }
  CONNECTIONS_ESTABLISHED.fetch_add(1, std::memory_order_relaxed);
  return sock;
}

static Order MakeOrder(uint64_t seq, uint32_t client, uint16_t instr,
                     OrderType type, uint64_t price, uint32_t qty, Side side) {
  Order order{};
  order.sequence_id = seq;
  order.timestamp_ns = 0;
  order.client_id = client;
  order.instrument_id = instr;
  order.type = type;
  order.price = price;
  order.quantity = (type == OrderType::CANCEL) ? 0 : qty;
  order.side = side;
  return order;
}

static bool SendOrderFrame(int sock, const Order &order) {
  if (send(sock, &order, sizeof(order), 0) !=
      static_cast<ssize_t>(sizeof(order))) {
    return false;
  }
  NETWORK_ORDERS_SENT.fetch_add(1, std::memory_order_relaxed);
  return true;
}

// Send one limit/market order. seq_id must be a fresh NextSeq().
bool SendOrder(int sock, uint64_t seq, uint32_t client, uint16_t instr,
               uint64_t price, uint32_t qty, Side side) {
  const Order order =
      MakeOrder(seq, client, instr, OrderType::LIMIT, price, qty, side);

  if (!SendOrderFrame(sock, order)) {
    RequestGracefulShutdown("Engine severed connection during send.");
    return false;
  }

  return true;
}

bool SendCancel(int sock, uint64_t target_seq, uint32_t client, uint16_t instr,
                Side side) {
  const Order order = MakeOrder(NextSeq(), client, instr, OrderType::CANCEL,
                                target_seq, 0, side);

  if (!SendOrderFrame(sock, order)) {
    RequestGracefulShutdown("Engine severed connection during cancel.");
    return false;
  }

  return true;
}

// Rate limiter: 1s window

struct RateLimiter {

  int target_per_sec;
  int ops_this_window{0};
  Clock::time_point window_start{Clock::now()};

  explicit RateLimiter(int tps) : target_per_sec(tps) {}

  void SetRate(int tps) { target_per_sec = tps; }

  // Call after each send.
  void Throttle() {
    ops_this_window++;
    if (ops_this_window >= target_per_sec) {
      auto elapsed = Clock::now() - window_start;
      auto budget = std::chrono::seconds(1);
      if (elapsed < budget)
        std::this_thread::sleep_for(budget - elapsed);
      window_start = Clock::now();
      ops_this_window = 0;
    }
  }
};

// =============================================================================
// Bot 1 — Market Maker
//
// Continuously posts BOOK_DEPTH bids and asks around mid.
// Refreshes every REFRESH_MS by cancelling all resting orders and re-posting.
// Rate scales with phase: 200 → 500 → 800 → 1500 orders/sec.
// =============================================================================

struct RestingOrder {
  uint64_t seq_id;
  Side side;
};

void MarketMakerBot(uint32_t client_id, uint16_t instr_id) {
  int sock = ConnectToEngine();
  if (sock < 0) {
    std::cerr << "[MM " << client_id << "] Connection failed\n";
    return;
  }

  static constexpr int REFRESH_MS = 2000;

  uint64_t mid = MidFor(instr_id);

  // different seed per bot
  std::mt19937 rng(client_id * 6364136223846793005ULL);

  std::vector<RestingOrder> resting;
  resting.reserve(BOOK_DEPTH * 2);

  RateLimiter rl(200);
  auto last_refresh = Clock::now();

  auto post_book = [&]() {
    for (int i = 1; i <= BOOK_DEPTH && !SHUTDOWN.load(); i++) {
      uint64_t bid_price = mid - static_cast<uint64_t>(i * SPREAD_TICK);
      uint64_t ask_price = mid + static_cast<uint64_t>(i * SPREAD_TICK);

      uint32_t qty = static_cast<uint32_t>(10 + (BOOK_DEPTH - i) * 5);

      uint64_t bid_seq = NextSeq();
      SendOrder(sock, bid_seq, client_id, instr_id, bid_price, qty, Side::BUY);
      resting.push_back({bid_seq, Side::BUY});
      rl.Throttle();

      uint64_t ask_seq = NextSeq();
      SendOrder(sock, ask_seq, client_id, instr_id, ask_price, qty, Side::SELL);
      resting.push_back({ask_seq, Side::SELL});
      rl.Throttle();
    }
  };

  auto cancel_all = [&]() {
    for (const auto &o : resting)
      SendCancel(sock, o.seq_id, client_id, instr_id, o.side);
    resting.clear();
  };

  while (!SHUTDOWN.load()) {
    FleetPhase p = PHASE.load();
    if (p == FleetPhase::DONE)
      break;
    else if (p == FleetPhase::RAMP)
      rl.SetRate(500);
    else if (p == FleetPhase::SUSTAIN)
      rl.SetRate(800);
    else if (p == FleetPhase::SLA_HUNT)
      rl.SetRate(1500);
    else
      rl.SetRate(200);

    // Refresh: cancel stale resting orders and re-post at current mid
    auto now = Clock::now();
    auto time_elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(
                            now - last_refresh)
                            .count();
    if (time_elapsed > REFRESH_MS) {
      cancel_all();
      last_refresh = Clock::now();
    }

    post_book();

    // Slight mid drift
    uint64_t drift = rng() % 3;
    uint64_t drift_val = drift * SPREAD_TICK;
    if (rng() % 2 == 0)
      mid += drift_val;
    else
      mid = (mid > drift_val) ? mid - drift_val : mid;
    mid = std::max(mid, static_cast<uint64_t>(BASE / 2));
  }

  cancel_all();
  close(sock);
  std::cout << "[MM " << client_id << "] Exiting.\n";
}

// =============================================================================
// Bot 2 — Aggressive Taker
//
// Inactive during WARMUP (lets the book build up first).
// Two behaviours, chosen randomly:
//   • Simple cross (75%): bid just above best ask / ask just below best bid.
//     Tests the single-match path.
//   • Deep sweep (25%): one huge bid or ask that crosses all BOOK_DEPTH
//     levels. Tests the O(n) matching loop and is the primary driver of
//     SLA breaches in the later phases.
// =============================================================================

void AggressiveTakerBot(uint32_t client_id) {
  int sock = ConnectToEngine();
  if (sock < 0) {
    std::cerr << "[Taker " << client_id << "] Connection failed\n";
    return;
  }

  std::mt19937 rng(client_id * 2654435761ULL);
  std::uniform_int_distribution<int> instr_dist(1, NUM_INSTRUMENTS);

  RateLimiter rl(50);

  while (!SHUTDOWN.load()) {
    FleetPhase p = PHASE.load();
    if (p == FleetPhase::WARMUP) {
      std::this_thread::sleep_for(std::chrono::milliseconds(500));
      continue;
    }
    if (p == FleetPhase::DONE)
      break;
    else if (p == FleetPhase::SUSTAIN)
      rl.SetRate(200);
    else if (p == FleetPhase::SLA_HUNT)
      rl.SetRate(600);
    else
      rl.SetRate(50);

    uint16_t instr = static_cast<uint16_t>(instr_dist(rng));
    uint64_t mid = MidFor(instr);

    bool do_sweep = (rng() % 4 == 0); // 25% deep sweeps

    if (do_sweep) {
      uint64_t edge = static_cast<uint64_t>(SPREAD_TICK * (BOOK_DEPTH + 2));
      uint32_t sweep_qty = 500;
      SendOrder(sock, NextSeq(), client_id, instr, mid + edge, sweep_qty,
                Side::BUY);
      rl.Throttle();
      SendOrder(sock, NextSeq(), client_id, instr, mid - edge, sweep_qty,
                Side::SELL);
      rl.Throttle();

    } else {
      uint64_t tick = static_cast<uint64_t>(SPREAD_TICK);
      SendOrder(sock, NextSeq(), client_id, instr, mid + tick + 1, 10,
                Side::BUY);
      rl.Throttle();
      SendOrder(sock, NextSeq(), client_id, instr, mid - tick - 1, 10,
                Side::SELL);
      rl.Throttle();
    }
  }

  close(sock);
  std::cout << "[Taker " << client_id << "] Exiting.\n";
}

// =============================================================================
// Bot 3 — Cancel Spammer
//
// Tests two distinct cancel paths:
//   • Phantom cancel: fires cancels for sequence IDs that were never created.
//     The engine must return gracefully without corrupting book state.
//   • Hot cancel: posts a resting order then immediately cancels it.
// Rate ramps with phase. Phantom probes are interspersed in all phases.
// =============================================================================

void CancelSpammerBot(uint32_t client_id) {
  int sock = ConnectToEngine();
  if (sock < 0) {
    std::cerr << "[Canceler " << client_id << "] Connection failed\n";
    return;
  }

  std::mt19937 rng(client_id * 31337ULL);
  std::uniform_int_distribution<int> instr_dist(1, NUM_INSTRUMENTS);
  std::uniform_int_distribution<uint64_t> phantom_dist(SEQ_MIN, SEQ_MAX);

  RateLimiter rl(100);

  while (!SHUTDOWN.load()) {
    FleetPhase p = PHASE.load();
    if (p == FleetPhase::DONE)
      break;
    else if (p == FleetPhase::RAMP || p == FleetPhase::SUSTAIN)
      rl.SetRate(300);
    else if (p == FleetPhase::SLA_HUNT)
      rl.SetRate(800);
    else
      rl.SetRate(100);

    uint16_t instr = static_cast<uint16_t>(instr_dist(rng));
    uint64_t mid = MidFor(instr);

    // Use a seq_id from a range the global counter will never reach
    SendCancel(sock, phantom_dist(rng), client_id, instr, Side::BUY);
    rl.Throttle();

    // Far from mid so doesn't match
    uint64_t real_seq = NextSeq();
    SendOrder(sock, real_seq, client_id, instr, mid - 200, 1, Side::BUY);
    rl.Throttle();
    SendCancel(sock, real_seq, client_id, instr, Side::BUY);
    rl.Throttle();

    // Cancel an order that was just cancelled.
    if (rng() % 8 == 0) {
      SendCancel(sock, real_seq, client_id, instr, Side::BUY);
      rl.Throttle();
    }
  }

  close(sock);
  std::cout << "[Canceler " << client_id << "] Exiting.\n";
}

// =============================================================================
// Bot 4 — Wash Trader
//
// A single client_id submits a resting bid, then submits a crossing ask.
// The engine MUST reject the incoming ask (not the resting bid) and emit
// no trade.
// =============================================================================

void WashTraderBot(uint32_t client_id) {
  int sock = ConnectToEngine();
  if (sock < 0) {
    std::cerr << "[WashTrader " << client_id << "] Connection failed\n";
    return;
  }

  std::mt19937 rng(client_id * 999983ULL);
  std::uniform_int_distribution<int> instr_dist(1, NUM_INSTRUMENTS);

  while (!SHUTDOWN.load()) {
    FleetPhase p = PHASE.load();
    if (p == FleetPhase::DONE)
      break;

    uint16_t instr = static_cast<uint16_t>(instr_dist(rng));
    uint64_t mid = MidFor(instr);

    uint64_t bid_seq = NextSeq();
    SendOrder(sock, bid_seq, client_id, instr, mid, 10, Side::BUY);
    usleep(8000); // 8ms — give the dispatcher time to enqueue it
    SendOrder(sock, NextSeq(), client_id, instr, mid - 1, 10, Side::SELL);
    usleep(8000);
    // clean up the resting bid in case the engine didn't reject the crossing
    // ask
    SendCancel(sock, bid_seq, client_id, instr, Side::BUY);

    std::this_thread::sleep_for(std::chrono::milliseconds(250));
  }

  close(sock);
  std::cout << "[WashTrader " << client_id << "] Exiting.\n";
}

// =============================================================================
// Bot 5 — Flood Bot
//
// Only active during SPIKE and SLA_HUNT. Fires limit orders as fast as the
// socket will accept them, no rate limiter. Random instrument, random price
// (far from mid to avoid constant matching slowing the loop),
// qty=1 to minimise per-order work in the engine.
//
// The goal is to maximise queue depth so the dispatcher thread cannot drain
// fast enough.
// =============================================================================

void FloodBot(uint32_t client_id) {
  int sock = ConnectToEngine();
  if (sock < 0) {
    std::cerr << "[Flood " << client_id << "] Connection failed\n";
    return;
  }

  std::mt19937 rng(client_id * 1234567891ULL);
  std::uniform_int_distribution<int> instr_dist(1, NUM_INSTRUMENTS);
  std::uniform_int_distribution<uint64_t> price_dist(1000, 5000);

  while (!SHUTDOWN.load()) {
    FleetPhase p = PHASE.load();
    if (p != FleetPhase::SPIKE && p != FleetPhase::SLA_HUNT) {
      std::this_thread::sleep_for(std::chrono::milliseconds(200));
      continue;
    }
    if (p == FleetPhase::DONE)
      break;
    uint16_t instr = static_cast<uint16_t>(instr_dist(rng));
    uint64_t price = price_dist(rng);
    Side side = (rng() % 2) ? Side::BUY : Side::SELL;
    SendOrder(sock, NextSeq(), client_id, instr, price, 1, side);
  }

  close(sock);
  std::cout << "[Flood " << client_id << "] Exiting.\n";
}

int main(int argc, char **argv) {
  signal(SIGPIPE, SIG_IGN);

  int group_id = 0;
  uint64_t test_starts_at_ms = 0;

  if (argc >= 3) {
    ENGINE_HOST = argv[1];
    ENGINE_PORT = static_cast<uint16_t>(std::stoi(argv[2]));
  }
  if (argc >= 4)
    group_id = std::stoi(argv[3]);
  if (argc >= 5)
    test_starts_at_ms = std::stoull(argv[4]);

  const uint64_t local_epoch_ms = NowEpochMs();

  uint64_t starting_seq = static_cast<uint64_t>(group_id) * 1000000000ULL + 1;
  SEQ.store(starting_seq);

  std::cout << "\n[Shard " << group_id << "] Starting bot fleet against "
            << ENGINE_HOST << ":" << ENGINE_PORT;
  if (test_starts_at_ms > 0) {
    const uint64_t elapsed_ms =
        NowEpochMs() > test_starts_at_ms ? NowEpochMs() - test_starts_at_ms : 0;
    std::cout << " (joining at global phase "
              << FleetPhaseName(FleetPhaseForElapsedMs(elapsed_ms)) << ")";
  }
  std::cout << "\n";

  if (test_starts_at_ms > 0) {
    const uint64_t elapsed_ms =
        NowEpochMs() > test_starts_at_ms ? NowEpochMs() - test_starts_at_ms : 0;
    PHASE.store(FleetPhaseForElapsedMs(elapsed_ms));
  } else {
    PHASE.store(FleetPhase::WARMUP);
  }

  std::vector<std::thread> threads;
  for (int instr = 1; instr <= NUM_INSTRUMENTS; ++instr) {
    threads.emplace_back(MarketMakerBot, 100 + instr, static_cast<uint16_t>(instr));
    threads.emplace_back(MarketMakerBot, 200 + instr, static_cast<uint16_t>(instr));
  }
  threads.emplace_back(AggressiveTakerBot, 301);
  threads.emplace_back(AggressiveTakerBot, 302);
  threads.emplace_back(AggressiveTakerBot, 303);
  threads.emplace_back(CancelSpammerBot, 401);
  threads.emplace_back(CancelSpammerBot, 402);
  threads.emplace_back(WashTraderBot, 501);
  threads.emplace_back(FloodBot, 601);
  threads.emplace_back(FloodBot, 602);
  threads.emplace_back(FloodBot, 603);
  threads.emplace_back(FloodBot, 604);

  RunPhaseController(test_starts_at_ms, local_epoch_ms);

  for (auto &t : threads)
    if (t.joinable())
      t.join();

  std::cout << "[Shard " << group_id << "] Orders sent: "
            << NETWORK_ORDERS_SENT.load() << "\n";
  return 0;
}